@echo off

SET QMAKESPEC=win32-msvc2010

SET QTDIR=%QTDIR_5_1_0%
SET BOOSTDIR=%BOOSTDIR_1_53%
SET QWTDIR=%QWTDIR_6_1_0%
SET GTESTDIR=%GTESTDIR_1_6_0%
SET GMOCKDIR=%GMOCKDIR_1_6_0%
SET XERCESDIR=%XERCESDIR_2_8%

SET WORKING_DIRECTORY=%cd%
SET SOURCEDIR=%WORKING_DIRECTORY%\..
SET QMAKE=%QTDIR%\bin\qmake
